# Change these first
owner: coder0987 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: MachTarok
    url: https://machtarok.com
  - name: MachSSO
    url: https://sso.smach.us
  - name: SMACH.US
    url: https://smach.us
  - name: Samuel Mach
    url: https://samuelmach.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.smach.us
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status | MachTarok, SMACH.US, and SamuelMach.com
  introTitle: "See the live status of MachTarok.com"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Taroky
      href: https://machtarok.com/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
